before_script:
  - '[ -f pytest_kafka/py.typed ]'  # Typing marker must exist.
  - apt-get update -qq && apt-get install -y -qq openjdk-8-jre-headless
  - ./setup.py kafka
  - '[ ! -d dist ]'
  - ./setup.py sdist
  - '[ -d dist ]'
  - pip install .[dev]
  - flake8
  - mypy .
  # Install the packaged project and make sure we're not importing another.
  - pip uninstall pytest-kafka -y
  - rm pytest_kafka -r
  - 'pip install dist/pytest-kafka-*.tar.gz'
  - py.test -vv -s --durations=0

test-3.5:
  image: python:3.5
  script:
    - 'true'

test-3.6:
  image: python:3.6
  script:
    - 'true'

test-3.7:
  image: python:3.7
  script:
    - 'true'
