before_script:
  - apt-get update -qq && apt-get install -y -qq openjdk-8-jre-headless
  - ./setup.py develop

test:
  image: python:3.6
  script:
  - flake8
  - mypy .
  - py.test -vv -s

test-3.5:
  image: python:3.5
  script:
  - py.test -vv -s

test-3.7:
  image: python:3.7
  script:
  - py.test -vv -s
